@startuml
'https://plantuml.com/sequence-diagram

header %date("dd MMMM YYYY")
footer Page %page% of %lastpage%
hide footbox

title Purchases Manager

actor Client
box
participant Purchase
participant InvoiceFactory
participant OrderFactory
participant Order
participant CustomerFactory
participant Customer
participant Invoice
participant PaymentService
participant QueryBuilder
end box
actor PaymentSystem

Client --> Purchase: Создать счет
activate Client
Purchase -> InvoiceFactory: Создает счет на оплату
InvoiceFactory -> OrderFactory: Создает заказ
create Order
OrderFactory -> Order: <<create>>
InvoiceFactory -> CustomerFactory: Определяет покупателя
create Customer
CustomerFactory -> Customer: <<define>>
create Invoice
InvoiceFactory -> Invoice: <<create>>
Client <-- Purchase: Счет создан
deactivate Client

Client --> Purchase: Оплатить счет
activate Client
Purchase -> PaymentService: Создает запрос в платежную систему
create QueryBuilder
PaymentService -> QueryBuilder: <<create>>
PaymentService -> PaymentSystem: Отправляет запрос
PaymentSystem --> Client: Перенаправление в платежную систему
Client -> PaymentSystem: Оплата
Client <-- PaymentSystem: Оповещение об оплате
deactivate Client

'newpage

Client --> Purchase: Подтвердить платеж
activate Client
Purchase -> PaymentService: Создает запрос в платежную систему
PaymentService -> QueryBuilder: <<create>>
PaymentService -> PaymentSystem: Отправляет запрос
Purchase <-- PaymentSystem: Данные платежа
Purchase --> Client: Платеж подтвержден
deactivate Client

Client --> Purchase: Закрыть счет
activate Client
Purchase -> InvoiceFactory: Закрывает счет
InvoiceFactory -> Invoice: <<destroy>>
destroy Invoice
Purchase -> OrderFactory: Закрывает заказ
OrderFactory -> Order: <<destroy>>
destroy Order
Client <-- Purchase: Счет закрыт
deactivate Client
@enduml